### ISSUE TITLE
Clicking in the search resets the cursor to the beginning of the editor

### ISSUE THREAD

**Issue by tylerecouture** [tylerecouture/summernote-ext-emoji-ajax#2]
Similar problem reported here:
https://github.com/summernote/awesome-summernote/issues/33#issuecomment-259417662

**Comment by tylerecouture** [comment]
Need to remember cursor location before editor loses focus then replace before inserting image.  This may help: https://stackoverflow.com/questions/13949059/persisting-the-changes-of-range-objects-after-selection-in-html/13950376#13950376

**Comment by tylerecouture** [comment]
Better: figure out how to use summernote API:
http://summernote.org/deep-dive/#saverange-restorerange
http://summernote.org/deep-dive/#onfocus-onblur

**Comment by tylerecouture** [comment]
https://github.com/summernote/summernote/issues/1611#issuecomment-287610642

**Comment by lqez** [comment]
Awesome!
